In [1]:
from utils import Conv_S, conv_with_S
import torch, pickle, os, pdb
import numpy as np

In [2]:
ABSpath = '/home/skuser'
data_path = os.path.join(ABSpath,'data')

device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
transfer_f = np.array(pickle.load(open(os.path.join(data_path,'transfer_f.pickle'),'rb')))
transfer_f = torch.from_numpy(transfer_f).to(device).type(torch.float)
transfer_f.requires_grad = False
shape = (12,4,4)
mul = lambda x: x[0] * x[1] * x[2]
transfer_f = torch.reshape(torch.arange(mul(shape), dtype=torch.float, device=device),shape)

In [3]:
torch.reshape(transfer_f,(4,12,4))

tensor([[[  0.,   1.,   2.,   3.],
         [  4.,   5.,   6.,   7.],
         [  8.,   9.,  10.,  11.],
         [ 12.,  13.,  14.,  15.],
         [ 16.,  17.,  18.,  19.],
         [ 20.,  21.,  22.,  23.],
         [ 24.,  25.,  26.,  27.],
         [ 28.,  29.,  30.,  31.],
         [ 32.,  33.,  34.,  35.],
         [ 36.,  37.,  38.,  39.],
         [ 40.,  41.,  42.,  43.],
         [ 44.,  45.,  46.,  47.]],

        [[ 48.,  49.,  50.,  51.],
         [ 52.,  53.,  54.,  55.],
         [ 56.,  57.,  58.,  59.],
         [ 60.,  61.,  62.,  63.],
         [ 64.,  65.,  66.,  67.],
         [ 68.,  69.,  70.,  71.],
         [ 72.,  73.,  74.,  75.],
         [ 76.,  77.,  78.,  79.],
         [ 80.,  81.,  82.,  83.],
         [ 84.,  85.,  86.,  87.],
         [ 88.,  89.,  90.,  91.],
         [ 92.,  93.,  94.,  95.]],

        [[ 96.,  97.,  98.,  99.],
         [100., 101., 102., 103.],
         [104., 105., 106., 107.],
         [108., 109., 110., 111.],
         [112., 

In [4]:
f = transfer_f.transpose(0,1).cpu().numpy()[:,::-1,:]
print(f)
for i in transfer_f.transpose(0,1):
    print(i)

[[[176. 177. 178. 179.]
  [160. 161. 162. 163.]
  [144. 145. 146. 147.]
  [128. 129. 130. 131.]
  [112. 113. 114. 115.]
  [ 96.  97.  98.  99.]
  [ 80.  81.  82.  83.]
  [ 64.  65.  66.  67.]
  [ 48.  49.  50.  51.]
  [ 32.  33.  34.  35.]
  [ 16.  17.  18.  19.]
  [  0.   1.   2.   3.]]

 [[180. 181. 182. 183.]
  [164. 165. 166. 167.]
  [148. 149. 150. 151.]
  [132. 133. 134. 135.]
  [116. 117. 118. 119.]
  [100. 101. 102. 103.]
  [ 84.  85.  86.  87.]
  [ 68.  69.  70.  71.]
  [ 52.  53.  54.  55.]
  [ 36.  37.  38.  39.]
  [ 20.  21.  22.  23.]
  [  4.   5.   6.   7.]]

 [[184. 185. 186. 187.]
  [168. 169. 170. 171.]
  [152. 153. 154. 155.]
  [136. 137. 138. 139.]
  [120. 121. 122. 123.]
  [104. 105. 106. 107.]
  [ 88.  89.  90.  91.]
  [ 72.  73.  74.  75.]
  [ 56.  57.  58.  59.]
  [ 40.  41.  42.  43.]
  [ 24.  25.  26.  27.]
  [  8.   9.  10.  11.]]

 [[188. 189. 190. 191.]
  [172. 173. 174. 175.]
  [156. 157. 158. 159.]
  [140. 141. 142. 143.]
  [124. 125. 126. 127.]
  [108. 10

In [5]:
# y = torch.rand((2, 150, transfer_f.size(1)),dtype=torch.float).to(device)
y = torch.reshape(torch.arange(2*20*transfer_f.size(1),dtype=torch.float,device=device), (2,20,transfer_f.size(1)))
for i in y:
    print(i)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.],
        [20., 21., 22., 23.],
        [24., 25., 26., 27.],
        [28., 29., 30., 31.],
        [32., 33., 34., 35.],
        [36., 37., 38., 39.],
        [40., 41., 42., 43.],
        [44., 45., 46., 47.],
        [48., 49., 50., 51.],
        [52., 53., 54., 55.],
        [56., 57., 58., 59.],
        [60., 61., 62., 63.],
        [64., 65., 66., 67.],
        [68., 69., 70., 71.],
        [72., 73., 74., 75.],
        [76., 77., 78., 79.]], device='cuda:0')
tensor([[ 80.,  81.,  82.,  83.],
        [ 84.,  85.,  86.,  87.],
        [ 88.,  89.,  90.,  91.],
        [ 92.,  93.,  94.,  95.],
        [ 96.,  97.,  98.,  99.],
        [100., 101., 102., 103.],
        [104., 105., 106., 107.],
        [108., 109., 110., 111.],
        [112., 113., 114., 115.],
        [116., 117., 118., 119.],
        [120., 121., 122., 123.],
        

In [6]:
print(Conv_S(y[0], s_filter=transfer_f,device=device))
print(Conv_S(y[1], s_filter=transfer_f,device=device))

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [5.6000e+01, 6.2000e+01, 6.8000e+01, 7.4000e+01],
        [3.0400e+02, 3.3200e+02, 3.6000e+02, 3.8800e+02],
        [1.0000e+03, 1.0660e+03, 1.1320e+03, 1.1980e+03],
        [2.4000e+03, 2.5200e+03, 2.6400e+03, 2.7600e+03],
        [4.7600e+03, 4.9500e+03, 5.1400e+03, 5.3300e+03],
        [8.3360e+03, 8.6120e+03, 8.8880e+03, 9.1640e+03],
        [1.3384e+04, 1.3762e+04, 1.4140e+04, 1.4518e+04],
        [2.0160e+04, 2.0656e+04, 2.1152e+04, 2.1648e+04],
        [2.8920e+04, 2.9550e+04, 3.0180e+04, 3.0810e+04],
        [3.9920e+04, 4.0700e+04, 4.1480e+04, 4.2260e+04],
        [5.3416e+04, 5.4362e+04, 5.5308e+04, 5.6254e+04],
        [6.9664e+04, 7.0792e+04, 7.1920e+04, 7.3048e+04],
        [8.7712e+04, 8.9032e+04, 9.0352e+04, 9.1672e+04],
        [1.0576e+05, 1.0727e+05, 1.0878e+05, 1.1030e+05],
        [1.2381e+05, 1.2551e+05, 1.2722e+05, 1.2892e+05],
        [1.4186e+05, 1.4375e+05, 1.4565e+05, 1.4754e+05],
        [1.599

In [7]:
from scipy.io import loadmat
a = loadmat(os.path.join(data_path,'s_test_data'))
transfer_f = torch.from_numpy(a['path_01']).to(device)
y = torch.from_numpy(a['y']).to(device).unsqueeze(0)

In [8]:
y.shape

torch.Size([1, 40000, 8])

In [11]:
b = conv_with_S(y.type(y.dtype), transfer_f, device=device)
print(b[0][8999])

tensor([0.9555, 0.9928, 1.0413, 0.5334, 0.3425, 0.7519, 0.5291, 0.2524],
       device='cuda:0', dtype=torch.float64)
